import AppKit
import Foundation

@MainActor
final class ClipboardMonitor {
    private let pasteboard: NSPasteboard
    private let state: AppState
    private var timer: Timer?
    private var lastChangeCount: Int

    private static let excludedTypeNames: Set<String> = [
        // De-facto convention used by password managers and sensitive sources.
        // https://nspasteboard.org documents these.
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        // Explicit password-manager pasteboard owners.
        "com.agilebits.onepassword",
        "com.bitwarden.desktop",
        "com.dashlane.dashlanephonefinal",
        "io.gozala.passwords",
        "be.cylonix.secretive"
    ]

    init(state: AppState, pasteboard: NSPasteboard = .general) {
        self.state = state
        self.pasteboard = pasteboard
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.poll()
            }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else {
            return
        }

        lastChangeCount = pasteboard.changeCount

        if isExcluded {
            return
        }

        if let text = pasteboard.string(forType: .string) {
            state.record(text)
        }
    }

    private var isExcluded: Bool {
        guard let types = pasteboard.types else {
            return false
        }
        for type in types where Self.excludedTypeNames.contains(type.rawValue) {
            return true
        }
        return false
    }
}
